set nocompatible              " be iMproved, required
set encoding=utf-8
set expandtab

filetype off                  " required
filetype plugin indent off

call plug#begin()
Plug 'tpope/vim-fugitive'
Plug 'leafgarland/typescript-vim'
Plug 'Quramy/vim-js-pretty-template'
Plug 'jason0x43/vim-js-indent'

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'vim-scripts/AutoClose'
Plug 'SirVer/ultisnips'
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'Yggdroot/indentLine'
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'honza/vim-snippets'
Plug 'mattn/emmet-vim'
Plug 'elixir-lang/vim-elixir'
Plug 'rust-lang/rust.vim'
Plug 'elmcast/elm-vim'
Plug 'racer-rust/vim-racer'
Plug 'w0rp/ale'
Plug 'posva/vim-vue'
Plug 'sbdchd/neoformat'
Plug 'prettier/vim-prettier', { 'do': 'yarn install' }
Plug 'calviken/vim-gdscript3'

filetype plugin indent on    " required
" All of your Plugins must be added before the following line
call plug#end()            " required

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

let g:deoplete#enable_at_startup = 1

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" Indent automatically depending on filetype

set autoindent

" Turn on line numbering. Turn it off with "set nonu"
set number

" Set syntax on
syntax on

"
au BufReadPost Jenkinsfile set syntax=groovy
au BufReadPost Jenkinsfile set filetype=groovy

" Case insensitive search
set ic
set smartcase
set incsearch

set ruler " Show cursor position."

" Higlhight search
set hls

" Wrap text instead of being on one line
set lbr

set showcmd " Display incomplete commands.
set showmode " Display the mode you're in.
set backspace=indent,eol,start " Intuitive backspacing.
set hidden " Handle multiple buffers better.
set wildmenu " Enhanced command line completion.
set wildmode=list:longest " Complete files like a shell.
set wrap " Turn on line wrapping.
set scrolloff=3 " Show 3 lines of context around the cursor.
set title " Set the terminal's title
set visualbell " No beeping.

" Setting shell for vim
set shell=sh

" UNCOMMENT TO USE
 set laststatus=2 " Show the status line all the time
 " Useful status information at bottom of screen
 set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\%)%P
 " NERDTree
 let NERDTreeShowHidden=0
 " CtrlP
 if executable('ag')
 " Use ag over grep
 set grepprg=ag\ --nogroup\ --nocolor
 " Use ag in CtrlP for listing files. Lightning fast and
 " respects .gitignore
 let g:ctrlp_user_command = 'ag -i %s -l --nocolor -g ""'
 " ag is fast enough that CtrlP doesn't need to cache
 let g:ctrlp_use_caching = 0
endif

map <C-n> :NERDTreeToggle

" Zencoding
"let g:user_zen_expandabbr_key='<C-e>'
let g:user_zen_settings = { 'erb': { 'extends': 'html' } }"

" Color Scheme
set t_Co=256
"color Tomorrow-Night
color molokai
let g:molokai_original = 0
let g:rehash256 = 1
colorscheme Tomorrow-Night "railscasts

hi Search term=reverse cterm=reverse gui=reverse ctermfg=237

set tabstop=2 softtabstop=2 expandtab shiftwidth=2 smarttab

" vertical cursor
au WinLeave * set nocursorline nocursorcolumn
au WinEnter * set cursorline
set cursorline

set mouse=a

nnoremap <c-p> :FZF<cr>

let g:airline#extensions#tabline#enabled = 1

" disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" search highligted text with double backslash
vnoremap // y/<C-R>"<CR>"

" Only do this part when compiled with support for autocommands
if has("autocmd")
    " Enable file type detection
    filetype on

    " Syntax of these languages is fussy over tabs Vs spaces
    autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
    autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
    autocmd FileType rs setlocal ts=2 sts=2 sw=2 expandtab

    " Customisations based on house-style (arbitrary)
    autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
    autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
    autocmd FileType javascript setlocal ts=4 sts=4 sw=4 expandtab

    " Treat .rss files as XML
    autocmd BufNewFile,BufRead *.rss setfiletype xml
endif

let NERDTreeShowHidden=1
let g:NERDTreeWinSize=70

" airline
let g:airline_powerline_fonts = 1
let g:indentLine_color_term = 239
map <C-V> <C-V>
map <C-k> :bnext<CR>
map <C-j> :bprev<CR>
map <C-l> :bnext<CR>
map <C-h> :bprev<CR>

" Trigger configuration. Do not use <tab> if you use
" https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-d>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" elm-format
let g:elm_format_autosave = 1

" ctrl-p search on git tracked files
let g:ctrlp_use_caching = 0
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor

    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
else
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
  let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<space>', '<cr>', '<2-LeftMouse>'],
    \ }
endif

map <F2> :mksession! ./.vim_session <cr> " Quick write session with F2
map <F3> :source ./.vim_session <cr>     " And load session with F3

let g:rustfmt_autosave = 1

set hidden
let g:racer_cmd = "~/.cargo/bin/racer"

setlocal indentkeys+=0

autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

if !exists("g:ycm_semantic_triggers")
  let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers['typescript'] = ['.']

let g:ale_linter_aliases = {'vue': ['vue', 'javascript']}
let g:ale_linters = {
      \ 'javascript': ['eslint', 'vls', 'tsserver'],
      \ 'vue': ['eslint', 'vls'],
      \ 'ruby': ['rails_best_practices', 'rubocop'],
      \ 'yaml': ['yamllint'],
      \ 'python': ['pylint'],
      \ 'sh': ['shellcheck'],
      \ 'rust': ['cargo', 'rustc'],
      \ 'lua': ['luac'],
      \}
let g:ale_fixers = {
      \   '*': ['remove_trailing_lines', 'trim_whitespace'],
      \   'javascript': ['prettier', 'eslint'],
      \   'css': ['prettier'],
      \   'ruby': ['rubocop'],
      \   'yaml': ['prettier'],
      \   'python': ['autopep8'],
      \   'rust': ['rustfmt'],
      \}

let g:ale_linters_explicit = 1
let g:ale_fix_on_save = 1
let g:ale_completion_enabled = 1
autocmd BufWritePre *.js Neoformat
autocmd BufWritePre *.vue Neoformat
